language: node_js
node_js:
  - '7'

sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - COMMIT_SHA=${TRAVIS_COMMIT::8}
    - DOCKER_ORG=builditdigital
    - DOCKER_REPO=bookit-web
    # Docker Login
    - secure: G7IzlXf11wy/DxBvgNR+ChCKTsUABbiYl8q/nLLY++d5AK86ZfX+fqVMHhUArRad4in4LYuMPyMaoOJOsh38iy52/g8erbHSQmwX6r+JzHpueUlCBee7MP8mMGRbQPKC6Z+ZM4/JiMVleID3/uIfqxDGhNDNsB8abQ76DQN1s4x/dxVNM7WOv9EuNe66wyOATxeQ6VJop2jB8bdhYU8vlxBh0UsDMgU1ItjjdsQaxbB2t1YBBXFEQwjCErYCYzA9phFkk7vcnioDoJpe/ZRB8QCYuQDa9xBi64C9Oy0hS60cseLdZa9xgz5CUIVfuds5Rogs6tMusqhJmuKdvs2erMZybF978BHVqHEoLaLZSYlF0IyNeyo4gaMxRZG6sqLlIPgREYR8OjsFv9ZLvkT/K7Fw23EMYBmRvBOVYQSS+cafBieAiW54HdNcaFH8+SW2/GjHz2wDhvRBckVcWVTKZRMPPttqXwq9ZQwfo5fqxJCChkIiwkMIz2Y2OMUsDtzqay0mQ9Q5PKTn0SPj0evoCyHc4Qoef5x/rOZWJ4SDq8wE/meIOYK7ivoR1H7yVraak6kP+MZ/J09UbEpGIxz442NuFCFCkuSMO7Q0tiLdpbGFnY28som4axNGpEX3Ij08bLmKsLkQ/xL1ct2sdh0xseLS6M849r4oazULAlLFL+8=
    - secure: MunCbXG6H+pstm/Gf5bVzFXCuICfcdYEcoHfEeGSeVHkBRRFXOrLLbgR66mfqkvaHStbZhEvgVM/VbMobIuJqg5axb8YAwsnn5zoyOw2CAu9Zlemztzmgvk52vhI00xh+r3Ih/8wAFpdP26UUs4zjV4ueeqGaeFtPfLNT9+5rp+ZaRn5fDPtiUJ0zCgBtNU2rDz1oHL3TgeGn7npPUzdGptmUTLycdAnzVwsE4Lk5W7HwLSxqNduHBbX2egZWa5FWrL94inj1bX0LhkTcF9qavSn218bb2Bu3a94HNtofL0Xh97PE+g8gqTR51a3fDStXdMcKaDTPK5bwE+hUR2UI95VE7Kz8Sc7welV5jPye7c9IbDZ88RQR2aLwcJY0t5NvWsuUXAkFzIdafS05aoiKLysZQXYUxWnfW4IFwRTm9RReUjgEj2wjyd0TGZlh+lC+aQOUnGBghWlV0tkts1n5Uh4HL5w9YzR/tIvfK499hSIowGLmUaYLhd5LRyQyPtJivdVB/lWTBIvVym6kQJahG1mb2ZJ8Xps3uMNx6SrB9ud5g03Ivoa8GWCki0JVb0WJzLkScYxGsmdXHppogz6dlMao7l2fcwtLz2z+bIzoUw1pZEsaXMCLq2MA+7DCy14ycODIaD3OCrOBi679e7PB7m2u7+0zQnaDtlWMFVM0jI=
    - AWS_DEFAULT_REGION=us-east-1
    - BOOKITURI=http://dev6-bookit-web.riglet.io
    - ECS_REPO=mthomas-bookit-dev6-web-ecr-repo
    - ECS_CLUSTER=mthomas-bookit-dev6-ECSCluster
    - ECS_SERVICE=mthomas-bookit-dev6-app-BookitWebService-WO45JV48Y50-Service-1REV0R2M2FF9B
    # AWS_ACCESS_KEY_ID (CloudFormation stack IAM account)
    - secure: 1A7F5ZCZ/7zo2kxVxM5U6Ct88vnuu4QhJukjWO47Um4bcUBwVuC07UDO/CjAp+jtM6LepJYBeDCc0Mjxp9xO/yUDXr7W6XtLFJzn/5kHeI4u8wq+aaM7al+kWqzeMH5pYUs8QbH7khpP+UgXXK6Q7S+/kppnFwQMzjPVvroBEfluRY1CBTm2XL0Z+Q0XqdKh0nEbYRBtKlBoqw6cI46TSyc4yxqDRVWubhghBCJ+QipLUayAditzyN4IHpBf+SAZcz3BJpNITmjaHPKjLOn8moP8RHZmn4tpMD8CRJeJDAKV7oXqWr0+hyu4kV+eY6UaiflnRkdXfeBnAuVqqkNN3bbG02ceIj0/ihKf5xbyaSID6FA0wT4Ugb84YWdh6awJdVuTeed0oxVVdtw/pDfZXG94s7kIwtyEB5AYncX3Er+sCWDL+mCpj6g2caldfvEDZLE5h5/U3UHrNfCVhMjtPBTupm3LpYKRffURclijZpn/7GLnBG4m9P9Dr5EVbrMDxiphJpmCFb5YR2sNxeCJZ6PPPusOUJhOOez7eNRnlH/gCKaCgj3sD60modnvuuqDRBqGwuAckAYBEpxilw/GSF0c74c+knPj2hvXZgZhddYpuKShuZh3t9s7+4cYWM6LEhhydU7eGUdH3G550eLhy/Sxd7bRp0Wk0A0kEHbnWpA=
    # AWS_SECRET_ACCESS_KEY (CloudFormation stack IAM account)
    - secure: LrwTR1TZ4WO4W0A+b6FJV+oarv9VuzsZqXu+JBJW97YxzJkHhjegalLcHkDbtBV04Iil9ipzX7cNMHEWBWa2qsh11yvyAQEOrSH788TSHH9GnsHVgHk0ZhUr1glrDstPxBu5NqZz4uBFLbK5dY1v5uZqxh0HH7rF3ph4vh0WRJ5rBPeJ/a5HUsdu3KUWbz0GVKHTgryh+pM5Ca3jcHJOsnAcQ46UdZR/NOeqHKYhJ3RSKtpQiqNwWj+shbgFUk2Spw/c/vWJTxE7iy29sqbtoexI+gOzEF0pcvadKAjn/mxq7p9XRWiid1d/Mkg4AaqMgorf/aVfp68aZtBMASQDZIxW7JDJAuB/FsokjP0Oa49j+lL8m6x4+5Z5jPVjVGWnL9/hpfQ4N7lX2GmYMRWRnuTaggtzRgVUFSovCBmnNaYuzN5KVJ8O73IubdBT0C1sFv+emFYXjDryzut4slL4Z1ICnhhahxWt7F0acYsYXkdnSqvIeKaHfFi93PjNdZhMcYnEQRrcOqRN8RuZjanByLLiVLyYwpWx9sGgq4PJV062DyBS6ebsFlvyDVGu4qlYXL6LN9ywi5h5g6jmV8CiEbXLsjoV0S2l9RkGzoTdTkKFDDhOZeyLx2GBmlIob+wgfVvgJ7UVw2c/MAG41mGHHxbGOTtr7FH1pMhqiyB+0DQ=

install:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "75-automate-create-travis-iam-user" ]]; then pip install awscli; fi

before_script:
  # Builds only when branch is master and this is NOT a PR
  - ./scripts/yarn-and-docker-build.sh

script:
  - yarn lint
  - yarn test:unit -- --colors --ci --silent
  # Runs functional tests only when branch is master and this is NOT a PR
  - ./scripts/run-dockerized-functional-tests.sh docker-compose.testcafe.aws.yml bookit_testcafe_aws

after_success:
  - ./scripts/run-coveralls.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/docker-tag-push-deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/get-deployment-scripts.sh
    on:
      branch: 75-automate-create-travis-iam-user
  - provider: script
    skip_cleanup: true
    script: ./scripts/temp-build.sh
    on:
      branch: 75-automate-create-travis-iam-user
  - provider: script
    skip_cleanup: true
    script: ./scripts/push-to-ecr.sh
    on:
      branch: 75-automate-create-travis-iam-user
  - provider: script
    skip_cleanup: true
    script: ./scripts/ecs-deploy.sh -c ${ECS_CLUSTER} -n ${ECS_SERVICE} -i 006393696278.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECS_REPO}
    on:
      branch: 75-automate-create-travis-iam-user

notifications:
  slack:
    rooms:
      - secure: "W6ngcqgzcmk6Vn/+q+D7Yvk74unBtEn19W9jye4HcKPh6L23S8PgKNop7ANRf/msmlYZkmxPhT3bPB+nrYiIKHXbraelOtsjVVssf0GfpjN95tT6IQlKSD9HASWQaLDpqY6OtNL5zRf7l1dkou6BD+vUjOs27oLSnGJtJguSUAWiJ23176P0LkfFOhpgHrduDQE8pP5k/lmx3zZX4gdT2Zv8OHzqMhSJEjDvIL6OI9EAbP8atkVNTYKDeJmuiBRuGp+St3Pf9dv2qBK88eixLDTdxS0jmtPQHBgqPRon3ess3VoOnognHhSg+4YAcr6na9e0kXbBnADnQcK1sDYSiLTvqAqJ4usIwxVRmGsBawNmyXr4zMieJ7gt1pj/CgNap5rS/47bb+hAQWwSLUEVntwXEqvoOEBGUHEFVW5oD2zbor95tqdTwi51GCgjqVGmkNar27X7sB5/qQb3iaeftUBcWk5E4LrDTnhFzA3YiaoHhwtzbKed4Fht/x1oCV3ImAaOO4MCPa4d05iclCU7begU3fdOWMLkap4sZvSVccD6rt8jjfBa8pTEt81QW1Xu2PQn1oVIdLlheQX3O7FiZ9gA9C4fbfDfMlwNnTRWNitKJFn7VM7pNaqYA3UpNN370umohWWc/0xEcQlHa723sQDUSixrhm+RQtcr2tKYALM="
    template:
      - "%{commit_message}"
      - ":cat: :sparkles: :cat:  :sparkles:  :cat: :sparkles: :cat:"
      - ":wrench: <%{build_url}|#%{build_number}>"
      - ":eye: (<%{compare_url}|%{commit}>)"
      - "%{repository_name}@%{branch} by %{author}"
