sudo: false
language: node_js
node_js:
  - '7'
cache: yarn

env:
  global:
    - secure: G7IzlXf11wy/DxBvgNR+ChCKTsUABbiYl8q/nLLY++d5AK86ZfX+fqVMHhUArRad4in4LYuMPyMaoOJOsh38iy52/g8erbHSQmwX6r+JzHpueUlCBee7MP8mMGRbQPKC6Z+ZM4/JiMVleID3/uIfqxDGhNDNsB8abQ76DQN1s4x/dxVNM7WOv9EuNe66wyOATxeQ6VJop2jB8bdhYU8vlxBh0UsDMgU1ItjjdsQaxbB2t1YBBXFEQwjCErYCYzA9phFkk7vcnioDoJpe/ZRB8QCYuQDa9xBi64C9Oy0hS60cseLdZa9xgz5CUIVfuds5Rogs6tMusqhJmuKdvs2erMZybF978BHVqHEoLaLZSYlF0IyNeyo4gaMxRZG6sqLlIPgREYR8OjsFv9ZLvkT/K7Fw23EMYBmRvBOVYQSS+cafBieAiW54HdNcaFH8+SW2/GjHz2wDhvRBckVcWVTKZRMPPttqXwq9ZQwfo5fqxJCChkIiwkMIz2Y2OMUsDtzqay0mQ9Q5PKTn0SPj0evoCyHc4Qoef5x/rOZWJ4SDq8wE/meIOYK7ivoR1H7yVraak6kP+MZ/J09UbEpGIxz442NuFCFCkuSMO7Q0tiLdpbGFnY28som4axNGpEX3Ij08bLmKsLkQ/xL1ct2sdh0xseLS6M849r4oazULAlLFL+8=
    - secure: MunCbXG6H+pstm/Gf5bVzFXCuICfcdYEcoHfEeGSeVHkBRRFXOrLLbgR66mfqkvaHStbZhEvgVM/VbMobIuJqg5axb8YAwsnn5zoyOw2CAu9Zlemztzmgvk52vhI00xh+r3Ih/8wAFpdP26UUs4zjV4ueeqGaeFtPfLNT9+5rp+ZaRn5fDPtiUJ0zCgBtNU2rDz1oHL3TgeGn7npPUzdGptmUTLycdAnzVwsE4Lk5W7HwLSxqNduHBbX2egZWa5FWrL94inj1bX0LhkTcF9qavSn218bb2Bu3a94HNtofL0Xh97PE+g8gqTR51a3fDStXdMcKaDTPK5bwE+hUR2UI95VE7Kz8Sc7welV5jPye7c9IbDZ88RQR2aLwcJY0t5NvWsuUXAkFzIdafS05aoiKLysZQXYUxWnfW4IFwRTm9RReUjgEj2wjyd0TGZlh+lC+aQOUnGBghWlV0tkts1n5Uh4HL5w9YzR/tIvfK499hSIowGLmUaYLhd5LRyQyPtJivdVB/lWTBIvVym6kQJahG1mb2ZJ8Xps3uMNx6SrB9ud5g03Ivoa8GWCki0JVb0WJzLkScYxGsmdXHppogz6dlMao7l2fcwtLz2z+bIzoUw1pZEsaXMCLq2MA+7DCy14ycODIaD3OCrOBi679e7PB7m2u7+0zQnaDtlWMFVM0jI=

notifications:
  slack:
    rooms:
      - secure: "W6ngcqgzcmk6Vn/+q+D7Yvk74unBtEn19W9jye4HcKPh6L23S8PgKNop7ANRf/msmlYZkmxPhT3bPB+nrYiIKHXbraelOtsjVVssf0GfpjN95tT6IQlKSD9HASWQaLDpqY6OtNL5zRf7l1dkou6BD+vUjOs27oLSnGJtJguSUAWiJ23176P0LkfFOhpgHrduDQE8pP5k/lmx3zZX4gdT2Zv8OHzqMhSJEjDvIL6OI9EAbP8atkVNTYKDeJmuiBRuGp+St3Pf9dv2qBK88eixLDTdxS0jmtPQHBgqPRon3ess3VoOnognHhSg+4YAcr6na9e0kXbBnADnQcK1sDYSiLTvqAqJ4usIwxVRmGsBawNmyXr4zMieJ7gt1pj/CgNap5rS/47bb+hAQWwSLUEVntwXEqvoOEBGUHEFVW5oD2zbor95tqdTwi51GCgjqVGmkNar27X7sB5/qQb3iaeftUBcWk5E4LrDTnhFzA3YiaoHhwtzbKed4Fht/x1oCV3ImAaOO4MCPa4d05iclCU7begU3fdOWMLkap4sZvSVccD6rt8jjfBa8pTEt81QW1Xu2PQn1oVIdLlheQX3O7FiZ9gA9C4fbfDfMlwNnTRWNitKJFn7VM7pNaqYA3UpNN370umohWWc/0xEcQlHa723sQDUSixrhm+RQtcr2tKYALM="
    template:
      - "%{commit_message}"
      - ":cat: :sparkles: :cat:  :sparkles:  :cat: :sparkles: :cat:"
      - ":wrench: <%{build_url}|#%{build_number}>"
      - ":eye: (<%{compare_url}|%{commit}>)"
      - "%{repository_name}@%{branch} by %{author}"
