language: node_js
node_js:
- '7'

env:
  global:
  - secure: G7IzlXf11wy/DxBvgNR+ChCKTsUABbiYl8q/nLLY++d5AK86ZfX+fqVMHhUArRad4in4LYuMPyMaoOJOsh38iy52/g8erbHSQmwX6r+JzHpueUlCBee7MP8mMGRbQPKC6Z+ZM4/JiMVleID3/uIfqxDGhNDNsB8abQ76DQN1s4x/dxVNM7WOv9EuNe66wyOATxeQ6VJop2jB8bdhYU8vlxBh0UsDMgU1ItjjdsQaxbB2t1YBBXFEQwjCErYCYzA9phFkk7vcnioDoJpe/ZRB8QCYuQDa9xBi64C9Oy0hS60cseLdZa9xgz5CUIVfuds5Rogs6tMusqhJmuKdvs2erMZybF978BHVqHEoLaLZSYlF0IyNeyo4gaMxRZG6sqLlIPgREYR8OjsFv9ZLvkT/K7Fw23EMYBmRvBOVYQSS+cafBieAiW54HdNcaFH8+SW2/GjHz2wDhvRBckVcWVTKZRMPPttqXwq9ZQwfo5fqxJCChkIiwkMIz2Y2OMUsDtzqay0mQ9Q5PKTn0SPj0evoCyHc4Qoef5x/rOZWJ4SDq8wE/meIOYK7ivoR1H7yVraak6kP+MZ/J09UbEpGIxz442NuFCFCkuSMO7Q0tiLdpbGFnY28som4axNGpEX3Ij08bLmKsLkQ/xL1ct2sdh0xseLS6M849r4oazULAlLFL+8=
  - secure: MunCbXG6H+pstm/Gf5bVzFXCuICfcdYEcoHfEeGSeVHkBRRFXOrLLbgR66mfqkvaHStbZhEvgVM/VbMobIuJqg5axb8YAwsnn5zoyOw2CAu9Zlemztzmgvk52vhI00xh+r3Ih/8wAFpdP26UUs4zjV4ueeqGaeFtPfLNT9+5rp+ZaRn5fDPtiUJ0zCgBtNU2rDz1oHL3TgeGn7npPUzdGptmUTLycdAnzVwsE4Lk5W7HwLSxqNduHBbX2egZWa5FWrL94inj1bX0LhkTcF9qavSn218bb2Bu3a94HNtofL0Xh97PE+g8gqTR51a3fDStXdMcKaDTPK5bwE+hUR2UI95VE7Kz8Sc7welV5jPye7c9IbDZ88RQR2aLwcJY0t5NvWsuUXAkFzIdafS05aoiKLysZQXYUxWnfW4IFwRTm9RReUjgEj2wjyd0TGZlh+lC+aQOUnGBghWlV0tkts1n5Uh4HL5w9YzR/tIvfK499hSIowGLmUaYLhd5LRyQyPtJivdVB/lWTBIvVym6kQJahG1mb2ZJ8Xps3uMNx6SrB9ud5g03Ivoa8GWCki0JVb0WJzLkScYxGsmdXHppogz6dlMao7l2fcwtLz2z+bIzoUw1pZEsaXMCLq2MA+7DCy14ycODIaD3OCrOBi679e7PB7m2u7+0zQnaDtlWMFVM0jI=

notifications:
  slack:
    secure: evjXIx2RsQ2teg1h4QkfVf5GJ8EAsK6KuJxzlfMQGvIHxTL/iOg8atMRfhWMstKRIeKSlYVBP8ECFZQp+d1r2KzY39HoZQZSFki9Wz7cEYrMntsWzpA+PwuT2uAx4+9aTlWrEfIDO/0vQBv/X21/b84KxwFAHO4ONb7h8QgB6OOJRfax12GVE8tI/fsoH7/PlJ7oKetgyRfRb5yT2z7Rl5eziJu1CJt5J5u1MQjl1WPKq5uKD1tQmvpPvOUYO9Pi//Nwz4YHF+daEaiq6a9pocYLFtSoZJsPT9rBq6IHv8+ehL8fn4oJBB+7BsRFX6idfhToUAt/MtP5VNE5PS3RTDQCcg07N1Vmg9h4vRwwIr6QjeKtt6ZFsIB7mr8l/WoqFJAB3C3YCc8/MnoTSAFQCYPbXloyQBpUSrjCyyNLSnctMj+4WZUPLkd4rkVVoXaK5xlWfymkiJ7hRHnXhMNl9RdgUQ+/zp5ziAuL3dQbeXAFCy3AU3k6pjZeY9BU5Z0wUNcvpYuMc6gSN20qv9xfkytC4iJcU937htkbnCjGGS0T0SALd0e7x5lpJ/TjVSFDVz7X6Xqm0rfvjIje7aUXqD0nUntBFcow0U/zROw5DOQHrRh95jW+FtWsVFNZk8+vLL8Wmvv2jXEPCH4s/wK+ccFmTO1gKTd3dnGhOU1FSQU=

sudo: required
services:
- docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      export IMG_VERSION=`node -p -e "require('./package.json').version"`;
      echo "Building $IMG_VERSION";
      docker build -t builditdigital/bookit-web:$IMG_VERSION .;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push builditdigital/bookit-web:$IMG_VERSION;
    fi
