language: node_js
node_js:
  - '7'

sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - COMMIT_SHA=${TRAVIS_COMMIT::8}
    - DOCKER_ORG=builditdigital
    - DOCKER_REPO=bookit-web
    # Docker Login
    - secure: G7IzlXf11wy/DxBvgNR+ChCKTsUABbiYl8q/nLLY++d5AK86ZfX+fqVMHhUArRad4in4LYuMPyMaoOJOsh38iy52/g8erbHSQmwX6r+JzHpueUlCBee7MP8mMGRbQPKC6Z+ZM4/JiMVleID3/uIfqxDGhNDNsB8abQ76DQN1s4x/dxVNM7WOv9EuNe66wyOATxeQ6VJop2jB8bdhYU8vlxBh0UsDMgU1ItjjdsQaxbB2t1YBBXFEQwjCErYCYzA9phFkk7vcnioDoJpe/ZRB8QCYuQDa9xBi64C9Oy0hS60cseLdZa9xgz5CUIVfuds5Rogs6tMusqhJmuKdvs2erMZybF978BHVqHEoLaLZSYlF0IyNeyo4gaMxRZG6sqLlIPgREYR8OjsFv9ZLvkT/K7Fw23EMYBmRvBOVYQSS+cafBieAiW54HdNcaFH8+SW2/GjHz2wDhvRBckVcWVTKZRMPPttqXwq9ZQwfo5fqxJCChkIiwkMIz2Y2OMUsDtzqay0mQ9Q5PKTn0SPj0evoCyHc4Qoef5x/rOZWJ4SDq8wE/meIOYK7ivoR1H7yVraak6kP+MZ/J09UbEpGIxz442NuFCFCkuSMO7Q0tiLdpbGFnY28som4axNGpEX3Ij08bLmKsLkQ/xL1ct2sdh0xseLS6M849r4oazULAlLFL+8=
    - secure: MunCbXG6H+pstm/Gf5bVzFXCuICfcdYEcoHfEeGSeVHkBRRFXOrLLbgR66mfqkvaHStbZhEvgVM/VbMobIuJqg5axb8YAwsnn5zoyOw2CAu9Zlemztzmgvk52vhI00xh+r3Ih/8wAFpdP26UUs4zjV4ueeqGaeFtPfLNT9+5rp+ZaRn5fDPtiUJ0zCgBtNU2rDz1oHL3TgeGn7npPUzdGptmUTLycdAnzVwsE4Lk5W7HwLSxqNduHBbX2egZWa5FWrL94inj1bX0LhkTcF9qavSn218bb2Bu3a94HNtofL0Xh97PE+g8gqTR51a3fDStXdMcKaDTPK5bwE+hUR2UI95VE7Kz8Sc7welV5jPye7c9IbDZ88RQR2aLwcJY0t5NvWsuUXAkFzIdafS05aoiKLysZQXYUxWnfW4IFwRTm9RReUjgEj2wjyd0TGZlh+lC+aQOUnGBghWlV0tkts1n5Uh4HL5w9YzR/tIvfK499hSIowGLmUaYLhd5LRyQyPtJivdVB/lWTBIvVym6kQJahG1mb2ZJ8Xps3uMNx6SrB9ud5g03Ivoa8GWCki0JVb0WJzLkScYxGsmdXHppogz6dlMao7l2fcwtLz2z+bIzoUw1pZEsaXMCLq2MA+7DCy14ycODIaD3OCrOBi679e7PB7m2u7+0zQnaDtlWMFVM0jI=
    - AWS_DEFAULT_REGION=us-east-1
    - BOOKITURI=http://dev6-bookit-web.riglet.io
    - ECS_REPO=mthomas-bookit-dev6-web-ecr-repo
    - ECS_CLUSTER=mthomas-bookit-dev6-ECSCluster
    - ECS_SERVICE=mthomas-bookit-dev6-app-BookitWebService-WO45JV48Y50-Service-1REV0R2M2FF9B
    # AWS_ACCESS_KEY_ID
    - secure: bTubxyQPM/NJr5zX3TY03e1PEGOADTB5DJsfKKbemI5F6HoFhNip91ZAQOdzjFNejofiC7llXoiQ8t674MAcXyXpLvK8lFZo+oVfkvntJ+onFWdKClC+enXStqhQkelaUHnaCd0xxIK3ZEpRoeyUayFssYAWgmTIF07PgH1J2BEECuw4m9iMJuAFiTRUjAXsI0GXhvV0P0N9JpcgH6g9RVaEF5ghd3Q6dmgh7aDZaVs/ufDYbuUd32zywhSZiV0nFZ5N9PbOkMujU/LeXTjecrVW3NB1Yr/R2KVRlsQp4S0LM4PEzzN3DVYeCRwI6icoB3VuS80yoVlb8cj50O6sOtRlbG6wjVOxSXoKH/KtUKEOYcPcbQiMNZQeWUIsBXZYvepE557Jv7nvRraekdaYUvyWjyaxrLJWzHrheJ2vY3T039n8Yf93DJqVs1Ic8AmuosAK2eKdYUNNTxrd5r9qbBW2pD16J9yBBYL5RjvG98hGdxrGBjW0DoZ5+FgZa9KxECzVuygTep55y2jRvZWThBE3+LQ0nai2QKp5dOa7NBMqpWvqptQTm+Zsd/G6TWhZTA+yEDZMAvdnYxCDPzuphiUE++41xkvOnIw7uVuQvq2nEHw9QBdc1CE+S3tg4WJrLvgffWZickuRkDJZxEt9CPPLU3aRvG+iMToA7KM2AXo=
    # AWS_SECRET_ACCESS_KEY
    - secure: N0277TJFhg/6l5Q9bbRH5btNm0WZtfRXsYo97RoZ5DK/g06vSPltceY41z5MNueF5EprtQLqV9qTijBDEXwovDZKahYisthQ6DXukbQxgrAWxeGgr+hhu8iDH2CgHuQMlxotJ4pRwd0SljNXiiWdPM1rdgW4D6yPGBuBpFjrqvILT8M1ubXOcfwvL96TaOky+F1FXIt8DzVVUppvpNyoNBwWqz4Bw+9HjxyILXQJ2IL9X4TnPYu91MGt7XUGEL4BKneMJQfzvqyt2WOHXzv3zCQUUmXMZGAySMhQrTInyY30HnR/NsNgXjCsilPzO6T1J23oS6thI+eKXlNRCpyiGKQHAmrKsAxJjkYC4kBOo86wCONToZQUDluUxJaSr8FbwUclmBEIktIPEWv4neuoGp/SW+zTDz39Ma6n4+FExIIOZzW7uSNarMM1+iUXc6pXywGLh/kTvZGT2l3BhJ3WUs8Y7WiLWdRFblORo0ChV48DgqaEgjfJ/U0WYpO6hLZcCCWX/DvYqFY7BoxgAxoeCtIEsJOIBZyCIDs9UOQUH3uZCUoSxUVxul3P6/8RIE+7Riotcrd9Nue6fURpUOHnVjutXgvRxleqK1FwvtaoRuKJgYje4UOtC5os5/MVXyKJ5mU5gVMB2tlSq9Skiz5KA7eYpy3KYhoUFCCdYAdtAgU=

install:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then pip install awscli; fi

before_script:
  # Builds only when branch is master and this is NOT a PR
  - ./scripts/yarn-and-docker-build.sh

script:
  - yarn lint
  - yarn test:unit -- --colors --ci --silent
  # Runs functional tests only when branch is master and this is NOT a PR
  - ./scripts/run-dockerized-functional-tests.sh docker-compose.testcafe.aws.yml

after_success:
  - ./scripts/run-coveralls.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/docker-tag-push-deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/get-deployment-scripts.sh
    on:
      branch: 74-aws-integrate-web-to-api
  - provider: script
    skip_cleanup: true
    script: ./scripts/temp-build.sh
    on:
      branch: 74-aws-integrate-web-to-api
  - provider: script
    skip_cleanup: true
    script: ./scripts/push-to-ecr.sh
    on:
      branch: 74-aws-integrate-web-to-api
  - provider: script
    skip_cleanup: true
    script: ./scripts/ecs-deploy.sh -c ${ECS_CLUSTER} -n ${ECS_SERVICE} -i 006393696278.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECS_REPO}
    on:
      branch: 74-aws-integrate-web-to-api

notifications:
  slack:
    rooms:
      - secure: "W6ngcqgzcmk6Vn/+q+D7Yvk74unBtEn19W9jye4HcKPh6L23S8PgKNop7ANRf/msmlYZkmxPhT3bPB+nrYiIKHXbraelOtsjVVssf0GfpjN95tT6IQlKSD9HASWQaLDpqY6OtNL5zRf7l1dkou6BD+vUjOs27oLSnGJtJguSUAWiJ23176P0LkfFOhpgHrduDQE8pP5k/lmx3zZX4gdT2Zv8OHzqMhSJEjDvIL6OI9EAbP8atkVNTYKDeJmuiBRuGp+St3Pf9dv2qBK88eixLDTdxS0jmtPQHBgqPRon3ess3VoOnognHhSg+4YAcr6na9e0kXbBnADnQcK1sDYSiLTvqAqJ4usIwxVRmGsBawNmyXr4zMieJ7gt1pj/CgNap5rS/47bb+hAQWwSLUEVntwXEqvoOEBGUHEFVW5oD2zbor95tqdTwi51GCgjqVGmkNar27X7sB5/qQb3iaeftUBcWk5E4LrDTnhFzA3YiaoHhwtzbKed4Fht/x1oCV3ImAaOO4MCPa4d05iclCU7begU3fdOWMLkap4sZvSVccD6rt8jjfBa8pTEt81QW1Xu2PQn1oVIdLlheQX3O7FiZ9gA9C4fbfDfMlwNnTRWNitKJFn7VM7pNaqYA3UpNN370umohWWc/0xEcQlHa723sQDUSixrhm+RQtcr2tKYALM="
    template:
      - "%{commit_message}"
      - ":cat: :sparkles: :cat:  :sparkles:  :cat: :sparkles: :cat:"
      - ":wrench: <%{build_url}|#%{build_number}>"
      - ":eye: (<%{compare_url}|%{commit}>)"
      - "%{repository_name}@%{branch} by %{author}"
