language: node_js
node_js:
  - '7'

sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - COMMIT_SHA=${TRAVIS_COMMIT::8}
    - DOCKER_ORG=builditdigital
    - DOCKER_REPO=bookit-web
    # Docker Login
    - secure: G7IzlXf11wy/DxBvgNR+ChCKTsUABbiYl8q/nLLY++d5AK86ZfX+fqVMHhUArRad4in4LYuMPyMaoOJOsh38iy52/g8erbHSQmwX6r+JzHpueUlCBee7MP8mMGRbQPKC6Z+ZM4/JiMVleID3/uIfqxDGhNDNsB8abQ76DQN1s4x/dxVNM7WOv9EuNe66wyOATxeQ6VJop2jB8bdhYU8vlxBh0UsDMgU1ItjjdsQaxbB2t1YBBXFEQwjCErYCYzA9phFkk7vcnioDoJpe/ZRB8QCYuQDa9xBi64C9Oy0hS60cseLdZa9xgz5CUIVfuds5Rogs6tMusqhJmuKdvs2erMZybF978BHVqHEoLaLZSYlF0IyNeyo4gaMxRZG6sqLlIPgREYR8OjsFv9ZLvkT/K7Fw23EMYBmRvBOVYQSS+cafBieAiW54HdNcaFH8+SW2/GjHz2wDhvRBckVcWVTKZRMPPttqXwq9ZQwfo5fqxJCChkIiwkMIz2Y2OMUsDtzqay0mQ9Q5PKTn0SPj0evoCyHc4Qoef5x/rOZWJ4SDq8wE/meIOYK7ivoR1H7yVraak6kP+MZ/J09UbEpGIxz442NuFCFCkuSMO7Q0tiLdpbGFnY28som4axNGpEX3Ij08bLmKsLkQ/xL1ct2sdh0xseLS6M849r4oazULAlLFL+8=
    - secure: MunCbXG6H+pstm/Gf5bVzFXCuICfcdYEcoHfEeGSeVHkBRRFXOrLLbgR66mfqkvaHStbZhEvgVM/VbMobIuJqg5axb8YAwsnn5zoyOw2CAu9Zlemztzmgvk52vhI00xh+r3Ih/8wAFpdP26UUs4zjV4ueeqGaeFtPfLNT9+5rp+ZaRn5fDPtiUJ0zCgBtNU2rDz1oHL3TgeGn7npPUzdGptmUTLycdAnzVwsE4Lk5W7HwLSxqNduHBbX2egZWa5FWrL94inj1bX0LhkTcF9qavSn218bb2Bu3a94HNtofL0Xh97PE+g8gqTR51a3fDStXdMcKaDTPK5bwE+hUR2UI95VE7Kz8Sc7welV5jPye7c9IbDZ88RQR2aLwcJY0t5NvWsuUXAkFzIdafS05aoiKLysZQXYUxWnfW4IFwRTm9RReUjgEj2wjyd0TGZlh+lC+aQOUnGBghWlV0tkts1n5Uh4HL5w9YzR/tIvfK499hSIowGLmUaYLhd5LRyQyPtJivdVB/lWTBIvVym6kQJahG1mb2ZJ8Xps3uMNx6SrB9ud5g03Ivoa8GWCki0JVb0WJzLkScYxGsmdXHppogz6dlMao7l2fcwtLz2z+bIzoUw1pZEsaXMCLq2MA+7DCy14ycODIaD3OCrOBi679e7PB7m2u7+0zQnaDtlWMFVM0jI=
    - AWS_DEFAULT_REGION=us-east-1
    - BOOKITURI=http://dev-bookit-server.riglet.io
    # This identifies what namespace to pull configuration from
    - ENVIRONMENT=dev
    - ECS_REPO=benaychh-bookit-dev-server-ecr-repo
    - ECS_CLUSTER=benaychh-bookit-dev-ECSCluster
    - ECS_SERVICE=benaychh-bookit-dev-app-BookitServerService-FL53YOOW3SR3-Service-EXZTM07RQDVZ
    # AWS_ACCESS_KEY_ID (CloudFormation stack IAM account)
    - secure: e6TDa4l925c4ieEfIYwMin0wD9XMmYKtR0POh2hLqzIO+ornHYu+mya6ogZaPHbGiSts6Y7NxJnAgdmUKe4Y+SN0JlsTDXUvnx6rlXltePaXGeREE4pI4TZHm6FUHHVti2qHCJfIouP1Bg41h/9JU7ROpag7r/+0E/TjTj+PUdfY7O1hTz+EBrJpU5kcWhtTzO1AmJmkifGG45sMYLUDFcjD2IgjH+IcscwAcR03UxdSg/6kLw9lzGT1X4EMBVVCRVK9Rmu9hsHJv35aslpGg1trjW0MDRFQCCO3eioP8BoZxhjDOQu8mTZX1FVGEUqe5Tu6jCE38qJxK2xLi+0MvRmCmSslYfV/nSpxzM1+P/G4tl4gu+Tw/h3tLUJV7atrdlKLj9bINdBDBoTtvHpwahAoRmxtAVSJHaZ1z4X23R1hft5dElzDNFwvZsWkhJjABlomJCFX6a31LpPXWZsIzkp82qWofgLJRVxWj9SibGqOtnQeQLJmZO7DGKkJknwa+yMPECCxw/dGHWD9WcFr19IDDua83oGJ96vTX+xeN59Pk5QGj/bZVqMkzuxgWKAayXTRVRkCECvoLgdJi/nHOBTu1dqH+E1ZTkxOzdLl1xCOWNA0SJJYBhTaEcjS70AIkqb1m53pqNFRU8bp7VG9jL7ai838fncq3Fw9x5LldQ0=
    # AWS_SECRET_ACCESS_KEY (CloudFormation stack IAM account)
    - secure: pOPXpgLld1/om6oN1ynbtJCyd3IXzemlVGeEFrALeMu2bIAX68CGzjXyDdo7g/7uuKPN15+9FYb1LqXMytV7VyxIvwgcf9su+NGLce/saPn53N3EHXWj2YMET7vCRWFVZBm7NDvmPCNtZ1z/X4fQU4kvBavPx9PtQM9C8getqYOpBjE20Muxn7+PNMCtW7GESfklcJXjirXQ9+IJxxDbg0fDssfallnQW7jtOQWlKV/CuyB/IZtQF81LxKkE9qxEI/YP/bZHLd0+05AQJFVMU/D/FeL9Y1XkklnI1mHhtGy7wBxnAl4p6TOnBy2vWvQVpBOf/zv+C0X79+emITIbiddX1lmcBeYGBqPxv9B3CiZ3uPBt92R4KrxrlfIWnDp6aA84Eltiy+NWI8OTLGbdWmo7L4uhucb0bAMf1/9lvDStXUb5inqoKquwdAKVte8T2qu91/Zv+aBxSkuNbd+kbYwRIF1ItLygk0mqpo+yyZbExD7wW0AUtevkGRnwQdfhuGIjht+QvPev6VFhJ2IJR8Q5tB3EsO6k3/zxDHiro5gHOl3S0xfK4bM/Fwi66/lM1DHlY4qXNfjYMo/enIrsvReaXRVFM26I9z734ZGU6Fox+LQUnynpj/rrn9hzHd+tDoneD9siaKTU1mG09Lu2PYovyp+Ulx0PalfzF/lp31Q=

install:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "33-deploy-to-ecs" ]]; then pip install awscli; fi

before_script:
  # Builds only when branch is master and this is NOT a PR
  - ./scripts/yarn-and-docker-build.sh

script:
  - yarn lint
  - yarn test:unit -- --colors --ci --silent

after_success:
  - ./scripts/run-coveralls.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/docker-tag-push-deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/get-deployment-scripts.sh
    on:
      branch: 33-deploy-to-ecs-benaychh
  - provider: script
    skip_cleanup: true
    script: ./scripts/temp-build.sh
    on:
      branch: 33-deploy-to-ecs-benaychh
  - provider: script
    skip_cleanup: true
    script: ./scripts/push-to-ecr.sh
    on:
      branch: 33-deploy-to-ecs-benaychh
  - provider: script
    skip_cleanup: true
    script: ./scripts/ecs-deploy.sh -c ${ECS_CLUSTER} -n ${ECS_SERVICE} -i 006393696278.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECS_REPO}
    on:
      branch: 33-deploy-to-ecs-benaychh

after_deploy:
  # Runs functional tests only when branch is master and this is NOT a PR
  - ./scripts/run-dockerized-functional-tests.sh docker-compose.testcafe.aws.yml bookit_testcafe_aws

notifications:
  slack:
    rooms:
      - secure: "W6ngcqgzcmk6Vn/+q+D7Yvk74unBtEn19W9jye4HcKPh6L23S8PgKNop7ANRf/msmlYZkmxPhT3bPB+nrYiIKHXbraelOtsjVVssf0GfpjN95tT6IQlKSD9HASWQaLDpqY6OtNL5zRf7l1dkou6BD+vUjOs27oLSnGJtJguSUAWiJ23176P0LkfFOhpgHrduDQE8pP5k/lmx3zZX4gdT2Zv8OHzqMhSJEjDvIL6OI9EAbP8atkVNTYKDeJmuiBRuGp+St3Pf9dv2qBK88eixLDTdxS0jmtPQHBgqPRon3ess3VoOnognHhSg+4YAcr6na9e0kXbBnADnQcK1sDYSiLTvqAqJ4usIwxVRmGsBawNmyXr4zMieJ7gt1pj/CgNap5rS/47bb+hAQWwSLUEVntwXEqvoOEBGUHEFVW5oD2zbor95tqdTwi51GCgjqVGmkNar27X7sB5/qQb3iaeftUBcWk5E4LrDTnhFzA3YiaoHhwtzbKed4Fht/x1oCV3ImAaOO4MCPa4d05iclCU7begU3fdOWMLkap4sZvSVccD6rt8jjfBa8pTEt81QW1Xu2PQn1oVIdLlheQX3O7FiZ9gA9C4fbfDfMlwNnTRWNitKJFn7VM7pNaqYA3UpNN370umohWWc/0xEcQlHa723sQDUSixrhm+RQtcr2tKYALM="
    template:
      - "%{commit_message}"
      - ":cat: :sparkles: :cat:  :sparkles:  :cat: :sparkles: :cat:"
      - ":wrench: <%{build_url}|#%{build_number}>"
      - ":eye: (<%{compare_url}|%{commit}>)"
      - "%{repository_name}@%{branch} by %{author}"
