language: node_js
node_js:
  - '7'

sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - COMMIT_SHA=${TRAVIS_COMMIT::8}
    - DOCKER_ORG=builditdigital
    - DOCKER_REPO=bookit-web
    # Docker Login
    - secure: G7IzlXf11wy/DxBvgNR+ChCKTsUABbiYl8q/nLLY++d5AK86ZfX+fqVMHhUArRad4in4LYuMPyMaoOJOsh38iy52/g8erbHSQmwX6r+JzHpueUlCBee7MP8mMGRbQPKC6Z+ZM4/JiMVleID3/uIfqxDGhNDNsB8abQ76DQN1s4x/dxVNM7WOv9EuNe66wyOATxeQ6VJop2jB8bdhYU8vlxBh0UsDMgU1ItjjdsQaxbB2t1YBBXFEQwjCErYCYzA9phFkk7vcnioDoJpe/ZRB8QCYuQDa9xBi64C9Oy0hS60cseLdZa9xgz5CUIVfuds5Rogs6tMusqhJmuKdvs2erMZybF978BHVqHEoLaLZSYlF0IyNeyo4gaMxRZG6sqLlIPgREYR8OjsFv9ZLvkT/K7Fw23EMYBmRvBOVYQSS+cafBieAiW54HdNcaFH8+SW2/GjHz2wDhvRBckVcWVTKZRMPPttqXwq9ZQwfo5fqxJCChkIiwkMIz2Y2OMUsDtzqay0mQ9Q5PKTn0SPj0evoCyHc4Qoef5x/rOZWJ4SDq8wE/meIOYK7ivoR1H7yVraak6kP+MZ/J09UbEpGIxz442NuFCFCkuSMO7Q0tiLdpbGFnY28som4axNGpEX3Ij08bLmKsLkQ/xL1ct2sdh0xseLS6M849r4oazULAlLFL+8=
    - secure: MunCbXG6H+pstm/Gf5bVzFXCuICfcdYEcoHfEeGSeVHkBRRFXOrLLbgR66mfqkvaHStbZhEvgVM/VbMobIuJqg5axb8YAwsnn5zoyOw2CAu9Zlemztzmgvk52vhI00xh+r3Ih/8wAFpdP26UUs4zjV4ueeqGaeFtPfLNT9+5rp+ZaRn5fDPtiUJ0zCgBtNU2rDz1oHL3TgeGn7npPUzdGptmUTLycdAnzVwsE4Lk5W7HwLSxqNduHBbX2egZWa5FWrL94inj1bX0LhkTcF9qavSn218bb2Bu3a94HNtofL0Xh97PE+g8gqTR51a3fDStXdMcKaDTPK5bwE+hUR2UI95VE7Kz8Sc7welV5jPye7c9IbDZ88RQR2aLwcJY0t5NvWsuUXAkFzIdafS05aoiKLysZQXYUxWnfW4IFwRTm9RReUjgEj2wjyd0TGZlh+lC+aQOUnGBghWlV0tkts1n5Uh4HL5w9YzR/tIvfK499hSIowGLmUaYLhd5LRyQyPtJivdVB/lWTBIvVym6kQJahG1mb2ZJ8Xps3uMNx6SrB9ud5g03Ivoa8GWCki0JVb0WJzLkScYxGsmdXHppogz6dlMao7l2fcwtLz2z+bIzoUw1pZEsaXMCLq2MA+7DCy14ycODIaD3OCrOBi679e7PB7m2u7+0zQnaDtlWMFVM0jI=
    - AWS_DEFAULT_REGION=us-east-1
    - S3_BUCKET_BASE=rig.hap.bookit.hap-dev
    - BOOKITURI=https://hap-dev-bookit-web.buildit.tools
    # This identifies what namespace to pull configuration from
    - INT_ENV_NAME=hap-dev
    - ECS_REPO=hap-bookit-web-ecr-repo
    - INT_ECS_CLUSTER=hap-bookit-hap-dev-ECSCluster
    - INT_ECS_SERVICE=hap-bookit-hap-dev-app-BookitWebService-PI2N9RRTJCO6-Service-1GPLXK5S3DSID
    - STG_ECS_CLUSTER=hap-bookit-hap-stg-ECSCluster
    - STG_ECS_SERVICE=hap-bookit-hap-stg-app-BookitWebService-A8H80ACLFE52-Service-145ONXI505FFA
    # AWS_ACCESS_KEY_ID (CloudFormation stack IAM account)
    - secure: QWjIjRpXhKq3hqO+Wfqe7wdJEZvduRD+g7OgF4b0ICbkC3Ff9NcQse+nV49PfQ1pC9qFYigXNAh5hB+LjSFW72jTj2WmJa2L/kHIuOtWS6ZN9PPgWiy50rvnHRGFE64dXKdNWmfEtEb41Dw3Kum6XucUbAnOnD0evm4D+lEaL42WzFu5qUDzaDLSgs5esVcEqKT7yPshj4ZVI14bxe4A90YSy9YAqc58W6+6kDspwFC5nqfnCV44phKjUylIYf0ufM97Pr/DjNleTjrRZqdDTwiZB+uYo/AjUKAloeVQPsNRT26QAs50kCVymxt73vqwc6wDAeyf5Ac3m4CE6cNtrTqgeiZ8JbjgEq0gYw3zyiGd5weyCDburTBAleGxhXuAexIUxbdA8kZitbcZzNp6fAIu5UYfWO2GQ6G8hdK5cGpPEfz6xD/wHoS9KeKCANIg4lbVBNm59gy7BwGKal0yeFu6DA55BF37p8i4nkJ6zXijeq8MQL1eLrLm0IvYBvKSVtbAPfbTrM7UX8/+d/XK+Mb+S6kTAg6VxMEpqQkvwIx4Zn8LWSLl55ZB6gz4DWsm/CAfhObQA79l7Bn3zQY5qKUROuQmIZjmpKY/lMbFq5rguSmrw54M7dpI8ArQJmlAGrzWlw7P2rsWNq71goM/XNQsf6bRKwj1Yh7P76iIntg=
    # AWS_SECRET_ACCESS_KEY (CloudFormation stack IAM account)
    - secure: M3lQktYdvKuhJHLZTeygc2f0bBIc5hx+wefAKMOHcXbAIrR10buXzp9uqxrR1n1NOJnqaXsO34YIj+ec/N8R6sfwxpXXOzmiC6zjngzcT8pE5SuhANLPUwM2hMdmrN/igofq/QBT2n5DdUAazsIKwo6i7Ha1LAp4+LeCbzm0B1jUgN8B0g5S4eH63NBQQNlL09LyBze3NEK0mgzJxC0zWsbMloXuGpY9DIfGgvdmkrJUbOhPmRP4wrVOQpmozwkDYfwJPVfSFvmF2ctwIQ33Jk6M2WzL571QgQm2wUYUx5CVGtktsUvqth8fnN+dABpeBRIm8E7LO3g/zX595qKqsAH+DJtWo8Qj8SAPgFnpGX4vbj1nf26nnyWhgz0B3VeCsH6B8mn+iZfeoYrh38mOcTCEFgpkbO4fwIF3F9i3qHKf6+p+Wysvm8E/Z1fVWwRnrvbjC02l7bjfNAuBgXzy0W99ZCbouZuniGoF8BxmhF5LrLk3sWRFprWGBDq1D9U7XGIC5v+QvzKIdgzG1HLWclllvdhWSuzeEmbhbw39qeYzyyoBGZUwB8Ol5MOxeP4zwxqzEGkiHVGUP1Il3xajTIZqDEDcPchmmimOTTX3iVwlvN3nglPvwn9wWX8vUqoV1qXcNp8+4fU0QikQ7RaA297WiM8pYfWnJ2rq7sRX+7M=

install:
  - yarn

script:
  - yarn lint
  - yarn test:unit -- --colors --ci --silent
  - if [[ -z "$TRAVIS_PULL_REQUEST" || $TRAVIS_PULL_REQUEST == "false" ]] && [[ -z "$TRAVIS_BRANCH" || $TRAVIS_BRANCH == "72-bookit-web-deploy-to-staging" ]]; then ./scripts/run-ci-cd.sh; fi

after_success:
  - ./scripts/run-coveralls.sh

notifications:
  slack:
    rooms:
      - secure: "W6ngcqgzcmk6Vn/+q+D7Yvk74unBtEn19W9jye4HcKPh6L23S8PgKNop7ANRf/msmlYZkmxPhT3bPB+nrYiIKHXbraelOtsjVVssf0GfpjN95tT6IQlKSD9HASWQaLDpqY6OtNL5zRf7l1dkou6BD+vUjOs27oLSnGJtJguSUAWiJ23176P0LkfFOhpgHrduDQE8pP5k/lmx3zZX4gdT2Zv8OHzqMhSJEjDvIL6OI9EAbP8atkVNTYKDeJmuiBRuGp+St3Pf9dv2qBK88eixLDTdxS0jmtPQHBgqPRon3ess3VoOnognHhSg+4YAcr6na9e0kXbBnADnQcK1sDYSiLTvqAqJ4usIwxVRmGsBawNmyXr4zMieJ7gt1pj/CgNap5rS/47bb+hAQWwSLUEVntwXEqvoOEBGUHEFVW5oD2zbor95tqdTwi51GCgjqVGmkNar27X7sB5/qQb3iaeftUBcWk5E4LrDTnhFzA3YiaoHhwtzbKed4Fht/x1oCV3ImAaOO4MCPa4d05iclCU7begU3fdOWMLkap4sZvSVccD6rt8jjfBa8pTEt81QW1Xu2PQn1oVIdLlheQX3O7FiZ9gA9C4fbfDfMlwNnTRWNitKJFn7VM7pNaqYA3UpNN370umohWWc/0xEcQlHa723sQDUSixrhm+RQtcr2tKYALM="
    template:
      - "%{commit_message}"
      - ":cat: :sparkles: :cat:  :sparkles:  :cat: :sparkles: :cat:"
      - ":wrench: <%{build_url}|#%{build_number}>"
      - ":eye: (<%{compare_url}|%{commit}>)"
      - "%{repository_name}@%{branch} by %{author}"
