language: node_js
node_js:
  - '7'

sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - COMMIT_SHA=${TRAVIS_COMMIT::8}
    - DOCKER_ORG=builditdigital
    - DOCKER_REPO=bookit-web
    # Docker Login
    - secure: G7IzlXf11wy/DxBvgNR+ChCKTsUABbiYl8q/nLLY++d5AK86ZfX+fqVMHhUArRad4in4LYuMPyMaoOJOsh38iy52/g8erbHSQmwX6r+JzHpueUlCBee7MP8mMGRbQPKC6Z+ZM4/JiMVleID3/uIfqxDGhNDNsB8abQ76DQN1s4x/dxVNM7WOv9EuNe66wyOATxeQ6VJop2jB8bdhYU8vlxBh0UsDMgU1ItjjdsQaxbB2t1YBBXFEQwjCErYCYzA9phFkk7vcnioDoJpe/ZRB8QCYuQDa9xBi64C9Oy0hS60cseLdZa9xgz5CUIVfuds5Rogs6tMusqhJmuKdvs2erMZybF978BHVqHEoLaLZSYlF0IyNeyo4gaMxRZG6sqLlIPgREYR8OjsFv9ZLvkT/K7Fw23EMYBmRvBOVYQSS+cafBieAiW54HdNcaFH8+SW2/GjHz2wDhvRBckVcWVTKZRMPPttqXwq9ZQwfo5fqxJCChkIiwkMIz2Y2OMUsDtzqay0mQ9Q5PKTn0SPj0evoCyHc4Qoef5x/rOZWJ4SDq8wE/meIOYK7ivoR1H7yVraak6kP+MZ/J09UbEpGIxz442NuFCFCkuSMO7Q0tiLdpbGFnY28som4axNGpEX3Ij08bLmKsLkQ/xL1ct2sdh0xseLS6M849r4oazULAlLFL+8=
    - secure: MunCbXG6H+pstm/Gf5bVzFXCuICfcdYEcoHfEeGSeVHkBRRFXOrLLbgR66mfqkvaHStbZhEvgVM/VbMobIuJqg5axb8YAwsnn5zoyOw2CAu9Zlemztzmgvk52vhI00xh+r3Ih/8wAFpdP26UUs4zjV4ueeqGaeFtPfLNT9+5rp+ZaRn5fDPtiUJ0zCgBtNU2rDz1oHL3TgeGn7npPUzdGptmUTLycdAnzVwsE4Lk5W7HwLSxqNduHBbX2egZWa5FWrL94inj1bX0LhkTcF9qavSn218bb2Bu3a94HNtofL0Xh97PE+g8gqTR51a3fDStXdMcKaDTPK5bwE+hUR2UI95VE7Kz8Sc7welV5jPye7c9IbDZ88RQR2aLwcJY0t5NvWsuUXAkFzIdafS05aoiKLysZQXYUxWnfW4IFwRTm9RReUjgEj2wjyd0TGZlh+lC+aQOUnGBghWlV0tkts1n5Uh4HL5w9YzR/tIvfK499hSIowGLmUaYLhd5LRyQyPtJivdVB/lWTBIvVym6kQJahG1mb2ZJ8Xps3uMNx6SrB9ud5g03Ivoa8GWCki0JVb0WJzLkScYxGsmdXHppogz6dlMao7l2fcwtLz2z+bIzoUw1pZEsaXMCLq2MA+7DCy14ycODIaD3OCrOBi679e7PB7m2u7+0zQnaDtlWMFVM0jI=
    - AWS_DEFAULT_REGION=us-east-1
    - BOOKITURI=https://int-bookit-web.buildit.tools
    # This identifies what namespace to pull configuration from
    - ENVIRONMENT=int
    - ECS_REPO=buildit-bookit-int-web-ecr-repo
    - ECS_CLUSTER=buildit-bookit-int-ECSCluster
    - ECS_SERVICE=buildit-bookit-int-app-BookitWebService-11KBRU3RSXKFS-Service-1Q911MZZ84ZBT
    # AWS_ACCESS_KEY_ID (CloudFormation stack IAM account)
    - secure: ngn5//jn+C7z4JsfEYQvV530u/3qRvLlaZo5cfPDsjyefvEh3RAaBUCu3pQOsHHJCv9OewYYfcjdL2+pPS+Mebbr1LsMumwrN5NOMFSXiwIc5lonlI797yI6divfbvoSpW5/vxTFDV5ZLood3+pNEwJMmr3ZTphsovohKhJIEjD7P71aPbESlJ/24BG8IQp9+qizvs1zBojoVXdaJAZARu/mPVQSFz0iX7CKQ4loABD1uFEOK0RQnGd+a+L8UGdTv0JkdQ1giwXkV5BsP38QrP+FKJWaRlaGI/Xx+CSTgNpfdy/c7n8ZoPIp4auiIwPQXgvZyt69DOXp1G9vhWvlau0xuStfbgUFPCDNqI5i/cI6cUgHlgY6tHUTRLNbXPCymVPo55nynjKfXPXysmMSlHV4QlRm5GM5NPZaFqJI7tvV0gHZ5Db9ydwbxG6xnHVNMYya7d+gW0pvvqbkYssC29klXYL+CAuiRSp/Ivx22rWOZFG4D0Ov4EW57RcVV29Kmtuxh7h2wAxRbJMOnhZ106Q0hOVfOKHlA1Ncvq32YOSweQYtU39yUvod0KxyYLU46yAE68qkVOuyUNhrvX8MzGSPQgUcMsmkMuRg/wrrePAdtB0fUEHmVfSRCOkbV0MsVdtIB7mv2W1oeBOR9i5FFs10nR496n2E6nwtSz3Rp5E=
    # AWS_SECRET_ACCESS_KEY (CloudFormation stack IAM account)
    - secure: VRkl1kc0RMkQHgILu98vhYDFKvSKTKL1h5ZaS+7xnmhUzbphpCNnLvEDMguas4E7xpOXA9nT6xlKlNhZduB07wNMBspsxBoC5yGNh/HtD8WnABwcajmn5FYnPEI1tXJ//+o+fynYx0pg+l4dHX5Kf/GfHaDI+qwU94MwMs0rpwld4r251jSGmD5+/12m1h6RPjyAliRUF2WZmk6NHFy2cOVVKwtApQ4xKDtOWzsG5wyP6XTV9kvWXdhff7lEXib5qPkFgJg+I+jQjSZaPrFxhxEwNUrLn97P8TZYmLsF/7CVy4cMBcCwON6f64w/zB28yv6FQRUdP1i/SNEHNU9gfP7sERQph5QPVjweqJRZ1uyoj2afXAxbtyZKrf8uAwrITHbIoaYGSpUkmBQ9i0QbGRuB1DwQddYDOEyNlttl2IE5K6G9Jvpusmd+NBAWvSBS4Cjq4GyrK3LBlOj10mOtOToV6QAfzNuixjYtq/dKaE/JlLyEOEzt35HDz6sHtrid/NGamyC1xaRPCwOivFQhoaQvWbNhjdoShPuy+lMoqHtmt28EjHF7827Ai0/jlix5pVkXYujzT8uepIpmTZgKsz71lwU2Yk3fS9/21Dt6+7XhWRaavnLzuogtbKah/cmc69bflfaoD2RMNM0ukNNPKILQ3BnWY8mtxBqrqsTpxzY=

install:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then pip install awscli; fi
  - yarn

before_script:
  # Builds only when branch is master and this is NOT a PR
  - ./scripts/yarn-and-docker-build.sh

script:
  - yarn lint
  - yarn test:unit -- --colors --ci --silent
  # Runs functional tests only when branch is master and this is NOT a PR
  # - ./scripts/run-dockerized-functional-tests.sh

after_success:
  - ./scripts/run-coveralls.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/docker-tag-push-deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/get-deployment-scripts.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/temp-build.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/push-to-ecr.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./scripts/ecs-deploy.sh -c ${ECS_CLUSTER} -n ${ECS_SERVICE} -i 006393696278.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECS_REPO}:${COMMIT_SHA}
    on:
      branch: master

after_deploy:
  # Runs functional tests only when branch is master and this is NOT a PR
  - ./scripts/run-dockerized-functional-tests.sh docker-compose.testcafe.aws.yml bookit_testcafe_aws

notifications:
  slack:
    rooms:
      - secure: "W6ngcqgzcmk6Vn/+q+D7Yvk74unBtEn19W9jye4HcKPh6L23S8PgKNop7ANRf/msmlYZkmxPhT3bPB+nrYiIKHXbraelOtsjVVssf0GfpjN95tT6IQlKSD9HASWQaLDpqY6OtNL5zRf7l1dkou6BD+vUjOs27oLSnGJtJguSUAWiJ23176P0LkfFOhpgHrduDQE8pP5k/lmx3zZX4gdT2Zv8OHzqMhSJEjDvIL6OI9EAbP8atkVNTYKDeJmuiBRuGp+St3Pf9dv2qBK88eixLDTdxS0jmtPQHBgqPRon3ess3VoOnognHhSg+4YAcr6na9e0kXbBnADnQcK1sDYSiLTvqAqJ4usIwxVRmGsBawNmyXr4zMieJ7gt1pj/CgNap5rS/47bb+hAQWwSLUEVntwXEqvoOEBGUHEFVW5oD2zbor95tqdTwi51GCgjqVGmkNar27X7sB5/qQb3iaeftUBcWk5E4LrDTnhFzA3YiaoHhwtzbKed4Fht/x1oCV3ImAaOO4MCPa4d05iclCU7begU3fdOWMLkap4sZvSVccD6rt8jjfBa8pTEt81QW1Xu2PQn1oVIdLlheQX3O7FiZ9gA9C4fbfDfMlwNnTRWNitKJFn7VM7pNaqYA3UpNN370umohWWc/0xEcQlHa723sQDUSixrhm+RQtcr2tKYALM="
    template:
      - "%{commit_message}"
      - ":cat: :sparkles: :cat:  :sparkles:  :cat: :sparkles: :cat:"
      - ":wrench: <%{build_url}|#%{build_number}>"
      - ":eye: (<%{compare_url}|%{commit}>)"
      - "%{repository_name}@%{branch} by %{author}"
