language: node_js
node_js:
- '7'
notifications:
  slack:
    secure: evjXIx2RsQ2teg1h4QkfVf5GJ8EAsK6KuJxzlfMQGvIHxTL/iOg8atMRfhWMstKRIeKSlYVBP8ECFZQp+d1r2KzY39HoZQZSFki9Wz7cEYrMntsWzpA+PwuT2uAx4+9aTlWrEfIDO/0vQBv/X21/b84KxwFAHO4ONb7h8QgB6OOJRfax12GVE8tI/fsoH7/PlJ7oKetgyRfRb5yT2z7Rl5eziJu1CJt5J5u1MQjl1WPKq5uKD1tQmvpPvOUYO9Pi//Nwz4YHF+daEaiq6a9pocYLFtSoZJsPT9rBq6IHv8+ehL8fn4oJBB+7BsRFX6idfhToUAt/MtP5VNE5PS3RTDQCcg07N1Vmg9h4vRwwIr6QjeKtt6ZFsIB7mr8l/WoqFJAB3C3YCc8/MnoTSAFQCYPbXloyQBpUSrjCyyNLSnctMj+4WZUPLkd4rkVVoXaK5xlWfymkiJ7hRHnXhMNl9RdgUQ+/zp5ziAuL3dQbeXAFCy3AU3k6pjZeY9BU5Z0wUNcvpYuMc6gSN20qv9xfkytC4iJcU937htkbnCjGGS0T0SALd0e7x5lpJ/TjVSFDVz7X6Xqm0rfvjIje7aUXqD0nUntBFcow0U/zROw5DOQHrRh95jW+FtWsVFNZk8+vLL8Wmvv2jXEPCH4s/wK+ccFmTO1gKTd3dnGhOU1FSQU=
