version: '2'

services:
  web:
    build: .
    ports:
     - "8080:80"
    environment:
    - API_BASE_URL=http://localhost:8888/
  server:
    image: bookit-server:local
    ports:
    - "8888:8888"
    #env_file: .env
    environment:
    - MICROSOFT_CLIENT_SECRET=setme_for_real_exchange

